imixs-archive-service/src/main/java/org/imixs/archive/service/ui/ClusterDataController.java
package org.imixs.archive.service.ui;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.Optional;
import java.util.logging.Logger;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.imixs.archive.service.ArchiveException;
import org.imixs.archive.service.cassandra.ClusterService;
import org.imixs.archive.service.cassandra.DataService;
import org.imixs.archive.service.resync.ResyncService;
import org.imixs.archive.service.util.MessageService;
import org.imixs.workflow.ItemCollection;

/**
 * CID Bean provide cluster configuration.
 * 
 * @author rsoika
 *
 */
@Named
@RequestScoped
public class ClusterDataController implements Serializable {

    private static final long serialVersionUID = 1L;

    private static Logger logger = Logger.getLogger(ClusterDataController.class.getName());

    String syncSizeUnit = null;
    ItemCollection metaData = null;

    @Inject
    ClusterService clusterService;

    @Inject
    DataService dataService;


    @Inject
    MessageService messageService;

    @Inject
    @ConfigProperty(name = ClusterService.ENV_ARCHIVE_CLUSTER_CONTACTPOINTS)
    Optional<String> contactPoint;

    @Inject
    @ConfigProperty(name = ClusterService.ENV_ARCHIVE_CLUSTER_KEYSPACE)
    Optional<String> keySpace;

    @Inject
    @ConfigProperty(name = ClusterService.ENV_ARCHIVE_CLUSTER_REPLICATION_FACTOR, defaultValue = "1")
    String repFactor;

    @Inject
    @ConfigProperty(name = ClusterService.ENV_ARCHIVE_CLUSTER_REPLICATION_CLASS, defaultValue = "SimpleStrategy")
    String repClass;

    @Inject
    @ConfigProperty(name = ClusterService.ENV_WORKFLOW_SERVICE_ENDPOINT)
    Optional<String> workflowServiceEndpoint;

    public ClusterDataController() {
        super();
    }

    /**
     * This method initializes a cluster and session obejct.
     * 
     * @throws ArchiveException
     * @see {@link ClusterDataController#close()}
     */
    @PostConstruct
    void init() {
        // load metadata
        try {
            metaData = dataService.loadMetadata();
        } catch (ArchiveException e) {
            logger.severe("Failed to load meta data!");
            e.printStackTrace();
        }
    }

    /**
     * Returns true if a connection to the specified keySpace was successful
     * 
     * @return true if session was successfull established.
     */
    public boolean isConnected() {
        return (clusterService.getSession() != null);
    }

   
    /**
     * returns the last reSync point of the current metaData object
     * 
     * @return
     */
    public Date getSyncPoint() {
        long lsyncPoint = metaData.getItemValueLong(ResyncService.ITEM_SYNCPOINT);
        Date syncPoint = new Date(lsyncPoint);
        return syncPoint;
    }

    public long getSyncCount() {
        return metaData.getItemValueLong(ResyncService.ITEM_SYNCCOUNT);
    }

    public String getSyncSize() {
        long l = metaData.getItemValueLong(ResyncService.ITEM_SYNCSIZE);
        String result = messageService.userFriendlyBytes(l);

        String[] parts = result.split(" ");
        syncSizeUnit = parts[1];
        return parts[0];
    }

    public String getSyncSizeUnit() {
        return syncSizeUnit;
    }

    public String getContactPoints() {
        return contactPoint.get();
    }

    public String getKeySpace() {
        return keySpace.get();
    }

    public String getReplicationFactor() {
        return repFactor;

    }

    public String getReplicationClass() {
        return repClass;
    }

    public String getServiceEndpoint() {
        return workflowServiceEndpoint.get();
    }

    /**
     * Returns the message list in reverse order.
     * 
     * @return
     */
    public List<String> getMessages() {
        List<String> messageLog = messageService.getMessages(ResyncService.MESSAGE_TOPIC);
        // revrese order (use cloned list)
        List<String> result = new ArrayList<String>();
        for (String message : messageLog) {
            result.add(message);
        }
        Collections.reverse(result);
        return result;
    }
}

imixs-archive-service/src/main/java/org/imixs/archive/service/ui/ErrorController.java
package org.imixs.archive.service.ui;

import java.io.Serializable;

import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Named;

/**
 * Session Scoped CID Bean to hold the current error messages.
 * 
 * @author rsoika
 *
 */
@Named
@SessionScoped
public class ErrorController implements Serializable {

    private static final long serialVersionUID = 1L;

    String message = null;

    public ErrorController() {
        super();
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * adds an error message to the current message.
     * 
     * @param message
     */
    public void addMessage(String message) {
        this.message += "\n" + message;
    }

    /**
     * reset the current error message
     */
    public void reset() {
        message = "";
    }

}

imixs-archive-service/src/main/java/org/imixs/archive/service/ui/RestoreController.java
package org.imixs.archive.service.ui;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;

import org.imixs.archive.service.ArchiveException;
import org.imixs.archive.service.cassandra.ClusterService;
import org.imixs.archive.service.cassandra.DataService;
import org.imixs.archive.service.restore.RestoreScheduler;
import org.imixs.archive.service.resync.ResyncService;
import org.imixs.archive.service.util.MessageService;
import org.imixs.workflow.ItemCollection;

import jakarta.annotation.PostConstruct;
import jakarta.ejb.Timer;
import jakarta.enterprise.context.SessionScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

/**
 * CID Bean for the resync service.
 * <p>
 * The syncpoint is managed as a string in the format 2019-12-31T06:00
 * 
 * 
 * 
 * @author rsoika
 *
 */
@Named
@SessionScoped
public class RestoreController implements Serializable {

    public static final String ISO_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";

    private static final long serialVersionUID = 1L;
    private static Logger logger = Logger.getLogger(RestoreController.class.getName());

    long restoreDateFrom;
    long restoreDateTo;
    String restoreSizeUnit = null;
    ItemCollection metaData = null;

    protected List<ItemCollection> options = null;

    @Inject
    ClusterService clusterService;

    @Inject
    DataService dataService;

    @Inject
    RestoreScheduler restoreService;

    @Inject
    MessageService messageService;

    public RestoreController() {
        super();
    }

    /**
     * This method initializes the default sync date
     * 
     */
    @PostConstruct
    void init() {
        reset();
    }

    /**
     * This method initializes the default sync date
     * 
     */
    public void reset() {
        try {
            // load metadata
            metaData = dataService.loadMetadata();
            // load options
            options = restoreService.getOptions(metaData);
        } catch (ArchiveException e) {
            logger.severe("Failed to load meta data!");
            e.printStackTrace();
        }
    }

    public String getRestoreFrom() {
        SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
        return dt.format(restoreDateFrom);

    }

    public void setRestoreFrom(String restorePoint) throws ParseException {
        if (restorePoint != null && !restorePoint.isEmpty()) {
            // update sync date...
            SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
            try {
                restoreDateFrom = dt.parse(restorePoint).getTime();
            } catch (ParseException e) {
                logger.severe("Unable to parse syncdate: " + e.getMessage());
            }
        }
    }

    public String getRestoreTo() {
        if (restoreDateTo == 0) {
            // default current time
            restoreDateTo = new Date().getTime();

            // NOTE:
            // Because the current syncPoint has milisecont precission, but we format the
            // restoreTo date in seconds only, we need to ajust the restoreTo timestamp per
            // 1 second! Otherwise the last snaspshot is typically excluded from the restore
            // because of its milisecond precission.
            restoreDateTo = restoreDateTo + 1000; // !!
        }
        SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
        return dt.format(restoreDateTo);
    }

    public void setRestoreTo(String restorePoint) {
        if (restorePoint != null && !restorePoint.isEmpty()) {
            // update sync date...
            SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
            try {
                restoreDateTo = dt.parse(restorePoint).getTime();
            } catch (ParseException e) {
                logger.severe("Unable to parse syncdate: " + e.getMessage());
            }
        }
    }

    /**
     * returns the syncpoint of the current configuration
     * 
     * @return
     */
    public Date getRestoreSyncPoint() {
        long lsyncPoint;
        lsyncPoint = metaData.getItemValueLong(RestoreScheduler.ITEM_RESTORE_SYNCPOINT);
        Date syncPoint = new Date(lsyncPoint);
        return syncPoint;
    }

    public long getRestoreCount() {
        return metaData.getItemValueLong(RestoreScheduler.ITEM_RESTORE_SYNCCOUNT);
    }

    public long getRestoreErrors() {
        return metaData.getItemValueLong(RestoreScheduler.ITEM_RESTORE_SYNCERRORS);
    }

    public String getRestoreSize() {
        long l = metaData.getItemValueLong(RestoreScheduler.ITEM_RESTORE_SYNCSIZE);
        String result = messageService.userFriendlyBytes(l);
        String[] parts = result.split(" ");
        restoreSizeUnit = parts[1];
        return parts[0];
    }

    public String getRestoreSizeUnit() {
        return restoreSizeUnit;
    }

    /**
     * returns the syncpoint of the current configuration
     * 
     * @return
     */
    public long getSyncPoint() {
        return metaData.getItemValueLong(ResyncService.ITEM_SYNCPOINT);
    }

    /**
     * returns the syncpoint of the current configuration
     * 
     * @return
     */
    public String getSyncPointISO() {
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS");
        Date date = new Date(getSyncPoint());
        return dt.format(date);
    }

    /**
     * This method starts a restore process
     * 
     * 
     */
    @SuppressWarnings("unchecked")
    public void startRestore() {
        try {
            logger.info("......init restore process: " + this.getRestoreFrom() + " to " + this.getRestoreTo());
            restoreService.setOptions(options, metaData);
            restoreService.start(restoreDateFrom, restoreDateTo,
                    metaData.getItemValue(RestoreScheduler.ITEM_RESTORE_OPTIONS));
        } catch (ArchiveException e) {
            logger.severe("failed to start restore process: " + e.getMessage());
        }

    }

    /**
     * This method cancels a current running sny process
     * 
     * @throws ArchiveException
     */
    public void stopRestore() {
        try {
            restoreService.cancel();
        } catch (ArchiveException e) {
            e.printStackTrace();
        }
    }

    /**
     * Returns true if a restore is running.
     * 
     * @return
     */
    public boolean isRunning() {
        Timer timer = restoreService.findTimer();
        return (timer != null);
    }

    public List<String> getMessages() {
        return messageService.getMessages(RestoreScheduler.MESSAGE_TOPIC);
    }

    /**
     * This methd returns a ItemCollection for each option
     * 
     * Example: <code>
     *   #{restoreController.options}
     * </code>
     * 
     * @return
     */
    public List<ItemCollection> getOptions() {
        return options;
    }

    public void setOptions(List<ItemCollection> options) {
        this.options = options;
    }

    /**
     * Adds a new filter option
     */
    public void addOption() {
        if (options == null) {
            options = new ArrayList<ItemCollection>();
        }

        ItemCollection itemCol = new ItemCollection();
        itemCol.replaceItemValue("type", "filter");
        options.add(itemCol);

    }

    /**
     * Removes an option by name
     * 
     * @param optionName
     */
    public void removeOption(String optionName) {
        if (options != null) {

            int iPos = 0;
            for (ItemCollection item : options) {
                if (optionName.equals(item.getItemValueString("name"))) {
                    options.remove(iPos);
                    break;
                }
                iPos++;
            }
        }
    }

}

imixs-archive-service/src/main/java/org/imixs/archive/service/ui/ResyncController.java
package org.imixs.archive.service.ui;

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Logger;

import org.imixs.archive.service.ArchiveException;
import org.imixs.archive.service.cassandra.ClusterService;
import org.imixs.archive.service.cassandra.DataService;
import org.imixs.archive.service.resync.ResyncService;
import org.imixs.archive.service.util.MessageService;
import org.imixs.workflow.ItemCollection;

import jakarta.annotation.PostConstruct;
import jakarta.enterprise.context.RequestScoped;
import jakarta.inject.Inject;
import jakarta.inject.Named;

/**
 * CID Bean for the resync service.
 * <p>
 * The new syncpoint is managed as a string in the format 2019-12-31T06:00
 * 
 * 
 * 
 * @author rsoika
 *
 */
@Named
@RequestScoped
public class ResyncController implements Serializable {

    public static final String ISO_DATETIME_FORMAT = "yyyy-MM-dd'T'HH:mm:ss";

    private static final long serialVersionUID = 1L;
    private static Logger logger = Logger.getLogger(ResyncController.class.getName());

    ItemCollection metaData = null;
    String newSyncPoint = null;

    @Inject
    ClusterService clusterService;

    @Inject
    ResyncService resyncService;

    @Inject
    DataService dataService;

    @Inject
    MessageService messageService;

    public ResyncController() {
        super();
    }

    /**
     * This method initializes the default sync date
     * 
     * @throws ArchiveException
     */
    @PostConstruct
    void init() {
        try {
            // load metadata
            metaData = dataService.loadMetadata();
        } catch (ArchiveException e) {
            logger.severe("Failed to load meta data!");
            e.printStackTrace();
        }
    }

    /**
     * Returns the newSyncPoint and computes the default value
     * 
     * @return
     */
    public String getNewSyncPoint() {
        if (newSyncPoint == null) {
            // compute default
            SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
            newSyncPoint = dt.format(getSyncPoint());

        }
        return newSyncPoint;
    }

    public void setNewSyncPoint(String newSyncPoint) {
        this.newSyncPoint = newSyncPoint;
    }

    /**
     * returns the syncpoint of the current configuration
     * 
     * @return
     */
    public Date getSyncPoint() {
        long lsyncPoint = metaData.getItemValueLong(ResyncService.ITEM_SYNCPOINT);
        Date syncPoint = new Date(lsyncPoint);
        return syncPoint;
    }

    /**
     * This method updates the current synpoint
     * 
     * @throws ArchiveException
     */
    public void updateSyncPoint() {
        try {
            // update sync date...
            SimpleDateFormat dt = new SimpleDateFormat(ISO_DATETIME_FORMAT);
            Date syncDate = dt.parse(newSyncPoint);
            logger.info("......updateing syncpoint=" + this.newSyncPoint);
            metaData.setItemValue(ResyncService.ITEM_SYNCPOINT, syncDate.getTime());
            dataService.saveMetadata(metaData);

            // restart sync?
            if (!resyncService.isRunning()) {
                resyncService.start();
            }

        } catch (ArchiveException | ParseException e) {
            logger.severe("failed to set new SyncPoint: " + e.getMessage());
        }

    }

    /**
     * Returns true if the sync service is actually running
     * 
     * @return
     */
    public boolean isRunning() {
        return resyncService.isRunning();
    }

    /**
     * This method cancels a current running sny process
     * 
     * @throws ArchiveException
     */
    public void cancel() {
        try {
            resyncService.cancel();
        } catch (ArchiveException e) {
            e.printStackTrace();
        }

    }

}

imixs-archive-service/src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<html>
<head>
<meta http-equiv="refresh" content="0; url=/monitor.xhtml" />
</head>
<body></body>
</html>

imixs-archive-service/src/main/webapp/monitor.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
	template="/layout/template.xhtml">


	<ui:define name="content">

		<h:form>
			<div class="imixs-form">
				<div class="imixs-header">
					<h1>
						<span class="typcn typcn-chart-bar-outline"></span>Monitor
					</h1>
				</div>

				<!-- Status Overview -->
				<div class="row">
					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Archive Status:</h1>
							<table style="width: 100%; margin-bottom: 10px;">

								<tr>
									<td style="width: 25%;">Cluster Contact Points:</td>
									<td>#{clusterDataController.contactPoints}</td>
								</tr>

								<tr>
									<td>KeySpace:</td>
									<td>#{clusterDataController.keySpace}</td>
								</tr>


								<tr>
									<td>Replication Factor:</td>
									<td>#{clusterDataController.replicationFactor}</td>
								</tr>
								<tr>
									<td>Replication Strategy:</td>
									<td>#{clusterDataController.replicationClass}</td>
								</tr>


								<tr>
									<td>Connecton Status:</td>
									<td><ui:fragment
											rendered="#{clusterDataController.connected}">
							OK <span class="typcn typcn-media-record"
												style="font-size: 1.3em; color: #5c9e5c;"></span>
										</ui:fragment> <ui:fragment rendered="#{!clusterDataController.connected}">
							Failed <span class="typcn typcn-media-record"
												style="font-size: 1.3em; color: #e84848;"></span>
										</ui:fragment></td>
								</tr>

								<tr>
									<td style="width: 25%;">Endpoint:</td>
									<td>#{clusterDataController.serviceEndpoint}</td>
								</tr>

							</table>


							<!-- load meta data -->
							<!-- html -->
							<a target="_blank" class="button" href="/api/archive/metadata">Metadata</a>
							<!-- xml -->
							<a target="_blank" class="button"
								href="/api/archive/metadata?format=xml">Metadata XML</a>
							<!-- json -->
							<a target="_blank" class="button"
								href="/api/archive/metadata?format=json">Metadata JSON</a>

						</div>
					</div>
				</div>
				

			</div>
		</h:form>
	</ui:define>
</ui:composition>

imixs-archive-service/src/main/webapp/restore.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
	template="/layout/template.xhtml">


	<h:head>
		<!--  reload the meta data object -->
		<f:metadata>
			<f:viewAction action="#{restoreController.reset()}" />
		</f:metadata>
	</h:head>
	
	<ui:define name="content">
	
		<ui:param name="isrunning" value="#{restoreController.isRunning()}"></ui:param>
	
		<h:form>
			<div class="imixs-form">
				<div class="imixs-header">
					<h1>
						<span class="typcn typcn-database"></span>Restore <h:outputText rendered="#{isrunning}" value=" - In Progress"  />
					</h1>
				</div>

				<div class="row">
					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Restore Snapshots:</h1>

							<p class="small">Define a Syncpoint to start a restore of
								existing snapshots into the workflow instance.</p>
							<table style="width: 100%;">

								<tr>
									<td style="width: 25%;">Last Archive Syncpoint:</td>
									<!-- format in ms -->
									<td>#{restoreController.syncPointISO}</td>
								</tr>

								<tr>
									<td>Restore from:</td>
									<td><h:inputText disabled="#{isrunning}" value="#{restoreController.restoreFrom}"></h:inputText>
										Format: yyyy-MM-dd'T'HH:mm:ss</td>
								</tr>

								<tr>
									<td>Restore to:</td>
									<td><h:inputText disabled="#{isrunning}" value="#{restoreController.restoreTo}"></h:inputText>
										Format: yyyy-MM-dd'T'HH:mm:ss</td>
								</tr>
							</table>
						</div>
					</div>

				</div>


				<!-- Options -->
				<div class="row">
					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Restore Options:</h1>
							<f:subview>
								<ui:include src="/sub_restore_options.xhtml" />
							</f:subview>
						</div>
					</div>
				</div>



				<!-- Status -->
				<div class="row">
					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Restore Status:</h1>
							<p class="lead" style="float: left; width: 32%;">
								<span class="typcn typcn-cloud-storage-outline"
									style="color: #5c9e5c;"></span>
								#{restoreController.restoreSize} <span style="font-size: 0.3em">#{restoreController.restoreSizeUnit}</span>
							</p>

							<p class="lead" style="float: left; width: 32%;">
								<span class="typcn typcn-arrow-repeat-outline"
									style="color: #5c9e5c;"></span>
								#{restoreController.restoreCount} <span style="font-size: 0.3em">total
									restored</span>
							</p>

							<p class="lead" style="">
								<span class="typcn typcn-flash-outline" style="color: #dd4929;"></span>
								#{restoreController.restoreErrors} <span style="font-size: 0.3em">Errors</span>
							</p>

							<p class="small">Last Restore Sync-Point:
								#{restoreController.restoreSyncPoint}</p>
						</div>
					</div>
				</div>

				<p style="margin-left: 10px;">
				
					<h:commandButton value="Refresh"
						action="restore?faces-redirect=true"
						rendered="#{isrunning}"></h:commandButton>
							
					<h:commandButton value="Start" action="restore?faces-redirect=true"
						rendered="#{!isrunning}"
						actionListener="#{restoreController.startRestore()}"></h:commandButton>

					<h:commandButton value="Stop"  action="restore?faces-redirect=true"
						rendered="#{isrunning}"
						actionListener="#{restoreController.stopRestore()}"></h:commandButton>
				</p>
			</div>


		</h:form>
	</ui:define>
</ui:composition>

imixs-archive-service/src/main/webapp/resync.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
	template="/layout/template.xhtml">

	<ui:define name="content">
		<h:form>
			<div class="imixs-form">
				<div class="imixs-header">
					<h1>
						<span class="typcn typcn-arrow-sync-outline"></span>Resync
					</h1>
				</div>

				<div class="row">
					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Sync-Point:</h1>

							<p class="small">Defining a new sync-point will perform a full or
								partial re-synchronization of the workflow instance.</p>
							<table style="width: 100%;">

								<tr>
									<td style="width: 25%;">Last Sync-Point:</td>
									<td>#{resyncController.syncPoint}</td>
								</tr>

								<tr>
									<td>Next Sync-Point:</td>
									<td><h:inputText name="syncPoint"
									  value="#{resyncController.newSyncPoint}"
									  disabled="#{resyncController.isRunning()}"></h:inputText>
										Format: yyyy-MM-dd'T'HH:mm:ss</td>
								</tr>
							</table>
						</div>
					</div>

				</div>

				
				
								<!-- Resync Status -->
				<div class="row">

					<div class="col-12">
						<div class="monitor-portlet">

							<h1><span>Resync Status: </span> 
							<ui:fragment
											rendered="#{resyncController.isRunning()}">
							<span class="typcn typcn-media-record"
												style="font-size: 1.3em; color: #5c9e5c;float:none"></span>
												<span> RUNNING</span>
										</ui:fragment> <ui:fragment rendered="#{!resyncController.isRunning()}">
							 <span class="typcn typcn-media-record"
												style="font-size: 1.3em; color: #e84848;float:none"></span><span> STOPPED</span>
										</ui:fragment></h1>

							<p class="lead" style="float: left; width: 48%;">
								<span class="typcn typcn-shopping-cart" style="color: #5c9e5c;"></span>
								#{clusterDataController.syncSize} <span style="font-size: 0.3em">#{clusterDataController.syncSizeUnit}</span>
							</p>

							<p class="lead" style="">
								<span class="typcn typcn-arrow-repeat-outline"
									style="color: #5c9e5c;"></span>
								#{clusterDataController.syncCount} <span
									style="font-size: 0.3em">total syncs</span>
							</p>

							<p class="small">Last ReSync:
								#{clusterDataController.syncPoint}  </p>
							
							<!-- Start / Stop sync scheduler -->
							<p style="margin-top: 10px;">
								<h:commandButton value="Refresh"
									action="resync?faces-redirect=true"
									rendered="#{resyncController.isRunning()}"></h:commandButton>
									
								<h:commandButton value="Start"
									action="resync?faces-redirect=true"
									rendered="#{!resyncController.isRunning()}"
									actionListener="#{resyncController.updateSyncPoint()}"></h:commandButton>

								<h:commandButton value="Stop"
									action="resync?faces-redirect=true"
									rendered="#{resyncController.isRunning()}"
									actionListener="#{resyncController.cancel()}"></h:commandButton>
							
							</p>


						</div>
					</div>
				</div>



				<!-- Resync Log -->
				<div class="row">


					<div class="col-12">
						<div class="monitor-portlet">
							<h1>Resync-Log:</h1>
							<p class="small">
								<ui:repeat var="entry" value="#{clusterDataController.messages}">
								#{entry}
								<br />
								</ui:repeat>
							</p>
						</div>
					</div>

				</div>

			</div>
		</h:form>
	</ui:define>
</ui:composition>